/*
 * Copyright (c) 2026, SiFli Technologies(Nanjing) Co, Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef SIFLI_MTP_RAM_USB_CONFIG_H
#define SIFLI_MTP_RAM_USB_CONFIG_H

#include "rtconfig.h"

#undef CONFIG_USBDEV_MTP_MAX_BUFSIZE
#undef CONFIG_USBDEV_MTP_MAX_OBJECTS
#undef CONFIG_USBDEV_MTP_MAX_PATHNAME
#undef CONFIG_USBDEV_MTP_MANUFACTURER
#undef CONFIG_USBDEV_MTP_MODEL
#undef CONFIG_USBDEV_MTP_DEVICE_VERSION
#undef CONFIG_USBDEV_MTP_SERIAL_NUMBER
#undef CONFIG_USBDEV_MTP_THREAD
#undef CONFIG_USBDEV_MTP_PRIO
#undef CONFIG_USBDEV_MTP_STACKSIZE

#define CONFIG_USBDEV_MTP_MAX_BUFSIZE 4096
#define CONFIG_USBDEV_MTP_MAX_OBJECTS 16
#define CONFIG_USBDEV_MTP_MAX_PATHNAME 256
#define CONFIG_USBDEV_MTP_MANUFACTURER "SiFli"
#define CONFIG_USBDEV_MTP_MODEL "SiFli MTP RAMDisk"
#define CONFIG_USBDEV_MTP_DEVICE_VERSION "1.00"
#define CONFIG_USBDEV_MTP_SERIAL_NUMBER "20260428"
#define CONFIG_USBDEV_MTP_THREAD
#define CONFIG_USBDEV_MTP_PRIO 4
#define CONFIG_USBDEV_MTP_STACKSIZE 4096

#define CONFIG_USBDEV_MTP_RAM_MAX_NODES 17
#define CONFIG_USBDEV_MTP_RAM_MAX_FILE_SIZE 8192
#define CONFIG_USBDEV_MTP_RAM_MAX_FDS 4
#define CONFIG_USBDEV_MTP_RAM_MAX_DIRS 8
#define CONFIG_USBDEV_MTP_RAM_NAME_LEN 64

#define CONFIG_USB_MUSB_SIFLI
#ifdef SOC_SF32LB58X
#define CONFIG_USB_HS
#endif

#include "cherryusb_config_template.h"

#endif
