[project]
name = "sifli-sdk-tools-default"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
  "coverage",
  "idf-build-apps",
  "jsonschema",
  "junit_xml",
  "python-gitlab",
  "pyyaml",
  "SimpleWebSocketServer",
  "pylint-gitlab",
  "minio",
  "prettytable",
  "setuptools",
  "packaging",
  "requests",
  "click",
  "pyserial",
  "cryptography",
  "pyparsing",
  "pyelftools",
  "pyclang",
  "construct",
  "rich",
  "psutil",
  "scons",
  "esp-idf-kconfig",
  "pycryptodome",
  "tqdm",
  "tomli_w",
  "conan",
  "semantic_version",
  "json5",
  "crccheck",
  "esp-docs",
  "linuxdoc",
  "gdbgui; sys_platform != 'win32' and python_version < '3.13'",
  "gdbgui; sys_platform == 'win32' and python_version < '3.11'",
  "pytest-embedded-serial-esp",
  "pytest-embedded-idf",
  "pytest-embedded-jtag",
  "pytest-embedded-qemu",
  "pytest-rerunfailures",
  "pytest-timeout",
  "pytest-ignore-test-results",
  "scapy",
  "websocket-client",
  "netifaces",
  "rangehttpserver",
  "dbus-python; sys_platform == 'linux'",
  "protobuf",
  "bleak",
  "paho-mqtt",
  "paramiko",
  "netmiko",
  "pyecharts",
  "python-can",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
